(()=>{
  const API='http://127.0.0.1:8080/agent/gateway';const $=id=>document.getElementById(id);const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  async function request(path){const response=await fetch(`${API}${path}`,{headers:{Accept:'application/json'}});const json=await response.json().catch(()=>({}));if(!response.ok||(json?.code&&json.code!==200))throw new Error(json?.message||`HTTP ${response.status}`);return json?.data??json}
  const verdict=value=>{const v=String(value||'unknown').toLowerCase();return v==='ok'||v==='ready'||v==='closed'?['可以使用','']:(v==='open'||v==='failed'||v==='error'?['需要处理','bad']:['等待确认','warn'])};
  const agentRoles={safety_gate:'安全守门员：脱敏与防提示攻击',crisis:'危机预警员：识别自伤等即时危险',emotion:'情绪分析员：提取情绪与证据',trend:'趋势观察员：识别长期变化',rag:'知识检索员：查找可信心理资料',risk:'风险评估员：给出可解释分级',profile:'画像更新员：记录长期状态变化',intervention:'干预建议员：制定可执行行动',follow_up:'跟进评估员：根据反馈调整方案',chat:'陪伴对话员：生成温和回复',evaluator:'质量检查员：检查安全和引用',audit:'审计记录员：保存决策依据'};
  const statusCard=(label,value,copy)=>{const [text,tone]=verdict(value);return `<article class="status-card"><span>${esc(label)}</span><strong><i class="dot ${tone}"></i>${esc(text)}</strong><small>${esc(copy)}</small></article>`};
  const kv=(label,value)=>`<div class="kv"><span>${esc(label)}</span><strong title="${esc(value)}">${esc(value??'—')}</strong></div>`;
  function render(data){const {health,ready,model,registry,rag}=data;const circuit=model?.circuit?.state||health?.model_gateway?.circuit_state;const agents=registry?.agents||[];$('updated-at').textContent=`最后刷新：${new Date().toLocaleString('zh-CN')} · 实时数据`; $('overview').innerHTML=[statusCard('后端服务',health?.status,health?.service||'—'),statusCard('模型服务',ready?.status,ready?.checks?.model_api_key_configured?'已配置':'未配置'),statusCard('调用保护',circuit,`连续失败 ${model?.circuit?.consecutive_failures??0} 次`),statusCard('注册 Agent',agents.length?'ok':'unknown',`${agents.length} 个`) ].join('');$('service-caption').textContent=`${health?.service||'系统服务'} · v${health?.version||'—'}`;$('service-list').innerHTML=[['健康检查','API',health?.status,health?.time],['就绪检查','AI',ready?.status,ready?.checks?.model_circuit_state||'—'],['调用保护','SAFE',circuit,health?.model_gateway?.configured?'模型网关已配置':'模型网关未配置']].map(([name,icon,status,detail])=>{const [label,tone]=verdict(status);return `<article class="service-row"><span class="service-icon">${icon}</span><span><strong>${esc(name)}</strong><small>${esc(detail||'—')}</small></span><b class="badge ${tone}">${esc(label)}</b></article>`}).join('');$('model-caption').textContent=model?.model||'—';$('model-grid').innerHTML=[kv('当前模型',model?.model),kv('配置状态',model?.configured?'已配置':'未配置'),kv('调用总数',model?.requests?.total),kv('成功 / 失败',`${model?.requests?.successful??0} / ${model?.requests?.failed??0}`),kv('平均耗时',model?.requests?.average_latency_ms==null?'—':`${Math.round(model.requests.average_latency_ms)} ms`),kv('保护状态',circuit)].join('');$('agent-caption').textContent=`实时注册 ${agents.length} 个`; $('agent-list').innerHTML=agents.length?agents.map(agent=>`<article class="agent"><div class="agent-top"><strong>${esc(agent.name)}</strong><small>v${esc(agent.version)}</small></div><p>${esc((agent.capabilities||[]).join(' · ')||'—')}</p></article>`).join(''):'<div class="empty">暂无 Agent 注册信息</div>';$('rag-caption').textContent=rag?.status==='ready'?'已就绪':'等待状态';$('rag-summary').innerHTML=[kv('文档数量',rag?.document_count),kv('知识片段',rag?.chunk_count),kv('知识分类',Array.isArray(rag?.categories)?rag.categories.length:'—'),kv('向量库',rag?.vector_store),kv('Embedding 模型',rag?.embedding_model),kv('状态',rag?.status)].join('')}
  async function load(){const button=$('refresh');button.disabled=true;button.textContent='正在刷新…';try{const [health,ready,model,registry,rag]=await Promise.all([request('/health'),request('/ready'),request('/model/status'),request('/agents/registry'),request('/rag/status')]);render({health,ready,model,registry,rag})}catch(error){$('updated-at').textContent=`读取失败：${error.message}`;$('overview').innerHTML='<div class="empty">服务状态暂时无法读取，请确认 Java 后端与 Python Agent 服务已启动。</div>'}finally{button.disabled=false;button.textContent='刷新状态'}}$('refresh').addEventListener('click',load);load();
})();
