import os
from pathlib import Path

from dotenv import load_dotenv


PROJECT_ROOT = Path(__file__).resolve().parents[1]
load_dotenv(PROJECT_ROOT / ".env")


def env(name: str, default: str = "") -> str:
    return os.getenv(name, default).strip()


MODEL_API_BASE_URL = env(
    "MODEL_API_BASE_URL",
    "https://dashscope.aliyuncs.com/compatible-mode/v1",
)
MODEL_API_KEY = env("MODEL_API_KEY")
MODEL_NAME = env("MODEL_NAME", "qwen-turbo")
MODEL_TIMEOUT_SECONDS = float(env("MODEL_TIMEOUT_SECONDS", "120"))
MODEL_MAX_RETRIES = int(env("MODEL_MAX_RETRIES", "2"))
MODEL_CIRCUIT_FAILURE_THRESHOLD = int(env("MODEL_CIRCUIT_FAILURE_THRESHOLD", "3"))
MODEL_CIRCUIT_RESET_SECONDS = float(env("MODEL_CIRCUIT_RESET_SECONDS", "30"))
HTTP_MAX_CONNECTIONS = int(env("HTTP_MAX_CONNECTIONS", "50"))
HTTP_MAX_KEEPALIVE_CONNECTIONS = int(env("HTTP_MAX_KEEPALIVE_CONNECTIONS", "20"))
HTTP_KEEPALIVE_EXPIRY_SECONDS = float(env("HTTP_KEEPALIVE_EXPIRY_SECONDS", "30"))

EMBEDDING_API_BASE_URL = env("EMBEDDING_API_BASE_URL", MODEL_API_BASE_URL)
EMBEDDING_API_KEY = env("EMBEDDING_API_KEY", MODEL_API_KEY)
EMBEDDING_MODEL = env("EMBEDDING_MODEL")
EMBEDDING_TIMEOUT_SECONDS = float(env("EMBEDDING_TIMEOUT_SECONDS", "60"))
EMBEDDING_MAX_RETRIES = int(env("EMBEDDING_MAX_RETRIES", "2"))
EMBEDDING_BATCH_SIZE = int(env("EMBEDDING_BATCH_SIZE", "32"))

RERANK_API_BASE_URL = env("RERANK_API_BASE_URL", EMBEDDING_API_BASE_URL)
RERANK_API_KEY = env("RERANK_API_KEY", EMBEDDING_API_KEY)
RERANK_MODEL = env("RERANK_MODEL", "BAAI/bge-reranker-v2-m3")
RERANK_TIMEOUT_SECONDS = float(env("RERANK_TIMEOUT_SECONDS", "60"))
RERANK_MAX_RETRIES = int(env("RERANK_MAX_RETRIES", "2"))
RERANK_INITIAL_MULTIPLIER = int(env("RERANK_INITIAL_MULTIPLIER", "4"))
RAG_VECTOR_CANDIDATE_THRESHOLD = float(env("RAG_VECTOR_CANDIDATE_THRESHOLD", "0.15"))
RAG_RERANK_ACCEPT_THRESHOLD = float(env("RAG_RERANK_ACCEPT_THRESHOLD", "0.35"))
RAG_RERANK_RAW_ACCEPT_THRESHOLD = float(env("RAG_RERANK_RAW_ACCEPT_THRESHOLD", "0.01"))
RAG_MAX_CITATIONS_PER_DOCUMENT = int(env("RAG_MAX_CITATIONS_PER_DOCUMENT", "2"))
RAG_CACHE_MAX_ENTRIES = int(env("RAG_CACHE_MAX_ENTRIES", "512"))
RAG_CACHE_TTL_SECONDS = float(env("RAG_CACHE_TTL_SECONDS", "1800"))
RAG_REQUEST_TIMEOUT_SECONDS = float(env("RAG_REQUEST_TIMEOUT_SECONDS", "2"))
RAG_INTENT_TIMEOUT_SECONDS = float(env("RAG_INTENT_TIMEOUT_SECONDS", "0.35"))
EMOTION_REQUEST_TIMEOUT_SECONDS = float(env("EMOTION_REQUEST_TIMEOUT_SECONDS", "2.5"))
# Streaming responses may spend several seconds waiting for the first token.
# Keep this aligned with the model gateway rather than cutting them off early.
CHAT_REQUEST_TIMEOUT_SECONDS = float(env("CHAT_REQUEST_TIMEOUT_SECONDS", "20"))
CHAT_MAX_TOKENS = int(env("CHAT_MAX_TOKENS", "600"))

VECTOR_STORE_BACKEND = env("VECTOR_STORE_BACKEND", "pgvector")
POSTGRES_HOST = env("POSTGRES_HOST", "127.0.0.1")
POSTGRES_PORT = int(env("POSTGRES_PORT", "5432"))
POSTGRES_DB = env("POSTGRES_DB")
POSTGRES_USER = env("POSTGRES_USER")
POSTGRES_PASSWORD = env("POSTGRES_PASSWORD")
POSTGRES_SSLMODE = env("POSTGRES_SSLMODE", "disable")
POSTGRES_CONNECT_TIMEOUT_SECONDS = max(1, int(env("POSTGRES_CONNECT_TIMEOUT_SECONDS", "3")))
PGVECTOR_SCHEMA = env("PGVECTOR_SCHEMA", "public")
PGVECTOR_TABLE = env("PGVECTOR_TABLE", "rag_chunks")
