"""Local RAG knowledge-base components."""

from .contracts import (
    KNOWLEDGE_CATEGORIES,
    SUPPORTED_DOCUMENT_EXTENSIONS,
    ChunkingConfig,
    ChunkingError,
    ChunkingSummary,
    ChunkEmbedding,
    DocumentParseError,
    KnowledgeCategory,
    KnowledgeChunk,
    KnowledgeParseSummary,
    ParsedDocumentMetadata,
    ParsedKnowledgeDocument,
    RerankItem,
    RerankSummary,
    RerankTraceItem,
    RetrievalCitation,
    RetrievalError,
    RetrievalSummary,
    VectorizationError,
    VectorizationSummary,
    VectorStoreError,
    VectorStoreSummary,
)
from .chunker import CHUNKER_VERSION, KnowledgeChunker, KnowledgeChunkerError
from .document_parser import (
    EmptyDocumentError,
    KnowledgeDocumentParser,
    KnowledgeDocumentParserError,
    UnsupportedDocumentTypeError,
)
from .embedding_gateway import (
    EmbeddingConfigurationError,
    EmbeddingGateway,
    EmbeddingGatewayError,
)
from .vectorizer import KnowledgeVectorizer, KnowledgeVectorizerError
from .retriever import KnowledgeRetrievalError, KnowledgeRetrievalService, PgVectorKnowledgeRetriever
from .reranker import (
    KnowledgeReranker,
    RerankConfigurationError,
    RerankGateway,
    RerankGatewayError,
    RerankedKnowledgeRetrievalService,
)
from .vector_store import (
    PgVectorKnowledgeStore,
    PgVectorStoreError,
    PostgresConfig,
    VectorStoreConfigurationError,
)

__all__ = [
    "KNOWLEDGE_CATEGORIES",
    "SUPPORTED_DOCUMENT_EXTENSIONS",
    "CHUNKER_VERSION",
    "ChunkingConfig",
    "ChunkingError",
    "ChunkingSummary",
    "ChunkEmbedding",
    "DocumentParseError",
    "EmbeddingConfigurationError",
    "EmbeddingGateway",
    "EmbeddingGatewayError",
    "EmptyDocumentError",
    "KnowledgeCategory",
    "KnowledgeChunk",
    "KnowledgeChunker",
    "KnowledgeChunkerError",
    "KnowledgeDocumentParser",
    "KnowledgeDocumentParserError",
    "KnowledgeReranker",
    "KnowledgeVectorizer",
    "KnowledgeVectorizerError",
    "KnowledgeParseSummary",
    "ParsedDocumentMetadata",
    "ParsedKnowledgeDocument",
    "RerankConfigurationError",
    "RerankGateway",
    "RerankGatewayError",
    "RerankedKnowledgeRetrievalService",
    "RerankItem",
    "RerankSummary",
    "RerankTraceItem",
    "RetrievalCitation",
    "RetrievalError",
    "RetrievalSummary",
    "UnsupportedDocumentTypeError",
    "VectorizationError",
    "VectorizationSummary",
    "PgVectorKnowledgeStore",
    "PgVectorStoreError",
    "PostgresConfig",
    "KnowledgeRetrievalError",
    "KnowledgeRetrievalService",
    "PgVectorKnowledgeRetriever",
    "VectorStoreConfigurationError",
    "VectorStoreError",
    "VectorStoreSummary",
]
